import { ReactNode } from "react";
import { fraunces, roboto_flex } from "./fonts";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: ReactNode;
  modal: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto_flex.variable} ${fraunces.variable}`}>
        <main className="mx-auto max-w-[1600px] px-[5%]">
          {props.children} {props.modal}
        </main>
      </body>
    </html>
  );
}
